// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVmA_us-_y2aRnwlLkkN6fJ49Gire6mI0',
    appId: '1:790288022513:web:3d1fc55bb5b289d971e250',
    messagingSenderId: '790288022513',
    projectId: 'spend-right',
    authDomain: 'spend-right.firebaseapp.com',
    storageBucket: 'spend-right.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWTrLmSh1jagkDevvqQfuOSYHvn-ptTY',
    appId: '1:790288022513:android:82eccadf83c0819771e250',
    messagingSenderId: '790288022513',
    projectId: 'spend-right',
    storageBucket: 'spend-right.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBhkhT-mKGW0vSXl3psLXJa1d8zCPtTlc',
    appId: '1:790288022513:ios:de256ff71190678f71e250',
    messagingSenderId: '790288022513',
    projectId: 'spend-right',
    storageBucket: 'spend-right.appspot.com',
    iosClientId: '790288022513-6706ci9tnbeckvijpeaaa3eoo3e7ejng.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendRight',
  );
}
